name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    name: build & lint
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm run lint
    - run: npm run build
